CREATE TABLE STORIES (
  STORYID NUMBER,
  TITLE VARCHAR2(128),
  CLOSED DATE,
  OPENED DATE,
  OWNER VARCHAR(32),
  PRIORITY NUMBER,
  PROJECTID NUMBER,
  STATE VARCHAR2(32),
  STORY VARCHAR2(1000),
  POINTS NUMBER(3),        
  PRIMARY KEY(STORYID)
);

CREATE INDEX  "BL_STORIES_OWNER" ON  "BL_BACKLOG" ("OWNER")
CREATE INDEX  "BL_STORIES_OPENED" ON  "BL_BACKLOG" ("OPENED")
CREATE INDEX  "BL_STORIES_POINTS" ON  "BL_BACKLOG" ("POINTS")
CREATE INDEX  "BL_STORIES_PROJECTID" ON  "BL_BACKLOG" ("PROJECTID")
CREATE INDEX  "BL_STORIES_PROJ_PRIORITY" ON  "BL_BACKLOG" ("PROJECTID", "PRIORITY")
CREATE INDEX  "BL_STORIES_PRIORITY" ON  "BL_BACKLOG" ("PRIORITY")
CREATE INDEX  "BL_STORIES_STATE" ON  "BL_BACKLOG" ("STATUS")

create sequence backlogStorySequence ; 