CREATE TABLE STORIES (
  STORYID NUMBER,
  TITLE VARCHAR2(128),
  CLOSED DATE,
  OPENED DATE,
  OWNER VARCHAR(32),
  PRIORITY NUMBER,
  PROJECTID NUMBER,
  STATE VARCHAR2(32),
  STORY VARCHAR2(1000),
  PRIMARY KEY(STORYID)
);

CREATE INDEX ON

create sequence backlogStorySequence ; 