DROP TABLE BL_STORIES if exists;
DROP TABLE BL_PROJECTS if exists;
DROP TABLE BL_GROUPS if exists;
DROP TABLE BL_GROUP_MEMBERS if exists;
DROP TABLE BL_PERSONS if exists;
DROP TABLE BL_ITERATION if exists;
DROP TABLE BL_ITERATION_TASK if exists;
DROP TABLE BL_EVENT if exists;
DROP TABLE BL_STORY_NOTES if exists;
DROP TABLE BL_META_CATEGORIES if exists;
DROP TABLE BL_STORY_CATEGORIES if exists;

DROP SEQUENCE "BL_STORY_SEQ" if EXISTS;
DROP SEQUENCE "BL_ITERATION_SEQ" if EXISTS;
DROP SEQUENCE "BL_ITER_TASK_SEQ" if EXISTS;

CREATE TABLE BL_STORIES (
STORYID IDENTITY,
TITLE VARCHAR(128),
CLOSED DATE,
OPENED DATE,
OWNER VARCHAR(32),
PRIORITY INT,
PROJECTID VARCHAR(32),
STATE VARCHAR(32),
STORY VARCHAR(1000),
POINTS INT,
PRIMARY KEY(STORYID)
);

CREATE INDEX  "BL_STORIES_OWNER" ON  "BL_STORIES" ("OWNER");
CREATE INDEX  "BL_STORIES_OPENED" ON  "BL_STORIES" ("OPENED");
CREATE INDEX  "BL_STORIES_POINTS" ON  "BL_STORIES" ("POINTS");
CREATE INDEX  "BL_STORIES_PROJECTID" ON  "BL_STORIES" ("PROJECTID");
CREATE INDEX  "BL_STORIES_PROJ_PRIORITY" ON  "BL_STORIES" ("PROJECTID", "PRIORITY");
CREATE INDEX  "BL_STORIES_PRIORITY" ON  "BL_STORIES" ("PRIORITY");
CREATE INDEX  "BL_STORIES_STATE" ON  "BL_STORIES" ("STATE");

CREATE SEQUENCE "BL_STORY_SEQ" START WITH 5 INCREMENT BY 1;

CREATE TABLE BL_PROJECTS (
  PROJECTID VARCHAR(32) NOT NULL,
  TITLE VARCHAR(128),
  DESCRIPTION VARCHAR(1000),
  CREATED DATE DEFAULT SYSDATE NOT NULL,
  STATE VARCHAR(32) DEFAULT 'new' NOT NULL,
  OWNER VARCHAR(32),
  PRIMARY KEY(PROJECTID)
);

CREATE INDEX "BL_PROJECTS_TITLE" ON "BL_PROJECTS" ("TITLE");
CREATE INDEX "BL_PROJECTS_STATE" ON "BL_PROJECTS" ("STATE");

CREATE TABLE BL_GROUPS (
  GROUPID VARCHAR(32) NOT NULL,
  TITLE VARCHAR(128),
  DESCRIPTION VARCHAR(1000),
  PRIMARY KEY(GROUPID)
);

CREATE TABLE BL_GROUP_MEMBERS (
  GROUPID VARCHAR(32) NOT NULL,
  MEMBERID VARCHAR(32),
  PRIMARY KEY(GROUPID,MEMBERID)
);

CREATE TABLE BL_PERSONS (
  "PERSONID" VARCHAR(32),
  "NAME" VARCHAR(64),
  PRIMARY KEY("PERSONID")
);

CREATE TABLE BL_ITERATION (
  "ITERATIONID" INT NOT NULL,
  "PROJECTID" VARCHAR(32) NOT NULL,
  "STARTDATE" DATE,
  "ACTIVEDAYS" INT,
  "COMPLETEDATE" DATE,
  "TITLE" VARCHAR(64),
  "STATE" VARCHAR(32),
  PRIMARY KEY("ITERATIONID")
);

CREATE SEQUENCE "BL_ITERATION_SEQ" START WITH 4 INCREMENT BY 1;

CREATE TABLE BL_ITERATION_TASK (
  "ITERATIONID" INT NOT NULL,
  "TASKID" INT NOT NULL,
  "STORYID" INT NOT NULL,
  "TITLE" VARCHAR(64) NOT NULL,
  "DESCRIPTION" VARCHAR(1000),
  "STATE" VARCHAR(32),
  "POINTS" INT,
  "STARTDATE" DATE,
  "COMPLETEDDATE" DATE,
  "ASSIGNED" VARCHAR(32),
  PRIMARY KEY ("TASKID")
);

CREATE SEQUENCE "BL_ITER_TASK_SEQ" START WITH 15 INCREMENT BY 1 ;

CREATE TABLE BL_EVENT (
  "EVENTID" INT NOT NULL,
  "TITLE" VARCHAR(32) NOT NULL,
  "DESCRIPTION" VARCHAR(500) NOT NULL,
  "OCCURED" DATE,
  PRIMARY KEY (EVENTID)
);

CREATE SEQUENCE "BL_EVENT_SEQ" START WITH 1 INCREMENT BY 1;

CREATE TABLE BL_STORY_NOTES (
  NOTEID INT NOT NULL,
  STORYID INT NOT NULL,
  TITLE VARCHAR(64) NOT NULL,
  CONTENT CLOB,
  PRIMARY KEY (NOTEID)
);

CREATE TABLE BL_META_CATEGORIES (
  CATEGORY VARCHAR(32),
  PRIMARY KEY (CATEGORY)
);

CREATE TABLE BL_STORY_CATEGORIES (
  STORYID INTEGER,
  CATEGORY VARCHAR(32),
  PRIMARY KEY (STORYID,CATEGORY)
);
